import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'category',
      label: '📚 Module 1: ROS 2',
      link: {
        type: 'doc',
        id: 'module1-ros2/intro',
      },
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module1-ros2'},
      ],
    },
    {
      type: 'category',
      label: '🤖 Module 2: Humanoid Robotics',
      link: {
        type: 'doc',
        id: 'module2-humanoid-robotics/intro',
      },
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module2-humanoid-robotics'},
      ],
    },
    {
      type: 'category',
      label: '🧠 Module 3: Physical AI',
      link: {
        type: 'doc',
        id: 'module3-physical-ai/intro',
      },
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'module3-physical-ai'},
      ],
    },
  ],
};

export default sidebars;
